# DDoS Detector Training

Training notebook placeholder.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
file_path = '/content/drive/MyDrive/spectra/ddo_mon_Jun_14.csv'
df1 = pd.read_csv(file_path)

display(df1.head())

,generated,appName,totalSourceBytes,totalDestinationBytes,totalDestinationPackets,totalSourcePackets,sourcePayloadAsBase64,sourcePayloadAsUTF,destinationPayloadAsBase64,destinationPayloadAsUTF,...,sourceTCPFlagsDescription,destinationTCPFlagsDescription,source,protocolName,sourcePort,destination,destinationPort,startDateTime,stopDateTime,Label
0,3/11/2014 18:21,Unknown_UDP,16076,0,0,178,NaN,NaN,NaN,NaN,...,NaN,NaN,192.168.5.122,udp_ip,5353,224.0.0.251,5353,6/13/2010 23:57,6/14/2010 0:11,Normal
1,3/11/2014 18:21,HTTPImageTransfer,384,0,0,6,NaN,NaN,NaN,NaN,...,"F,A",NaN,192.168.2.111,tcp_ip,4435,206.217.198.186,80,6/13/2010 23:58,6/14/2010 0:01,Normal
2,3/11/2014 18:21,DNS,171,642,4,2,NaN,NaN,NaN,NaN,...,NaN,NaN,192.168.4.119,udp_ip,4428,192.168.5.122,53,6/13/2010 23:58,6/13/2010 23:59,Normal
3,3/11/2014 18:21,HTTPImageTransfer,384,0,0,6,NaN,NaN,NaN,NaN,...,"F,A",NaN,192.168.4.119,tcp_ip,3639,219.94.203.105,80,6/13/2010 23:58,6/14/2010 0:00,Normal
4,3/11/2014 18:21,HTTPImageTransfer,186,128,2,2,NaN,NaN,NaN,NaN,...,"F,P,A",R,192.168.4.119,tcp_ip,3641,98.137.80.50,80,6/13/2010 23:58,6/13/2010 23:59,Normal

In [ ]:
file_path = '/content/drive/MyDrive/spectra/ddo_tue_jun_15.csv'
df2 = pd.read_csv(file_path)

display(df2.head())

,generated,appName,totalSourceBytes,totalDestinationBytes,totalDestinationPackets,totalSourcePackets,sourcePayloadAsBase64,sourcePayloadAsUTF,destinationPayloadAsBase64,destinationPayloadAsUTF,...,sourceTCPFlagsDescription,destinationTCPFlagsDescription,source,protocolName,sourcePort,destination,destinationPort,startDateTime,stopDateTime,Label
0,3/11/2014 16:24,BitTorrent,391223,4114484,7322,5650,NaN,NaN,NaN,NaN,...,"F,P,A","F,P,A",192.168.2.107,tcp_ip,1989,80.246.149.72,6880,6/14/2010 21:54,6/15/2010 1:43,Normal
1,3/11/2014 16:24,Unknown_UDP,236345,5324121,4282,3378,NaN,NaN,NaN,NaN,...,NaN,NaN,192.168.2.107,udp_ip,58040,96.238.239.35,24457,6/14/2010 21:54,6/15/2010 0:52,Normal
2,3/11/2014 16:24,Unknown_UDP,410420,11797592,9416,5791,NaN,NaN,NaN,NaN,...,NaN,NaN,192.168.2.107,udp_ip,58040,220.126.251.32,27295,6/14/2010 21:55,6/15/2010 1:54,Normal
3,3/11/2014 16:24,BitTorrent,127588,2949293,2249,1853,NaN,NaN,NaN,NaN,...,"P,A","F,R,P,A",192.168.2.107,tcp_ip,2048,92.126.24.44,44817,6/14/2010 21:56,6/15/2010 0:53,Normal
4,3/11/2014 16:24,Unknown_UDP,389781,11382564,8837,5531,NaN,NaN,NaN,NaN,...,NaN,NaN,192.168.2.107,udp_ip,58040,67.173.154.16,53341,6/14/2010 21:57,6/15/2010 1:54,Normal

In [ ]:


df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171380 entries, 0 to 171379
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   generated                       171380 non-null  object
 1   appName                         171380 non-null  object
 2   totalSourceBytes                171380 non-null  int64
 3   totalDestinationBytes           171380 non-null  int64
 4   totalDestinationPackets         171380 non-null  int64
 5   totalSourcePackets              171380 non-null  int64
 6   sourcePayloadAsBase64           84579 non-null   object
 7   sourcePayloadAsUTF              0 non-null       float64
 8   destinationPayloadAsBase64      74634 non-null   object
 9   destinationPayloadAsUTF         74616 non-null   object
 10  direction                       171380 non-null  object
 11  sourceTCPFlagsDescription       122074 non-null  object
 12  destinationTCPFlagsDescription  117397 non-null  object
 13  source                          171380 non-null  object
 14  protocolName                    171380 non-null  object
 15  sourcePort                      171380 non-null  int64
 16  destination                     171380 non-null  object
 17  destinationPort                 171380 non-null  int64
 18  startDateTime                   171380 non-null  object
 19  stopDateTime                    171380 non-null  object
 20  Label                           171380 non-null  object
dtypes: float64(1), int64(6), object(14)
memory usage: 27.5+ MB

In [ ]:
df1.isnull().sum()

generated                              0
appName                                0
totalSourceBytes                       0
totalDestinationBytes                  0
totalDestinationPackets                0
totalSourcePackets                     0
sourcePayloadAsBase64              86801
sourcePayloadAsUTF                171380
destinationPayloadAsBase64         96746
destinationPayloadAsUTF            96764
direction                              0
sourceTCPFlagsDescription          49306
destinationTCPFlagsDescription     53983
source                                 0
protocolName                           0
sourcePort                             0
destination                            0
destinationPort                        0
startDateTime                          0
stopDateTime                           0
Label                                  0
dtype: int64

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571698 entries, 0 to 571697
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   generated                       571698 non-null  object
 1   appName                         571698 non-null  object
 2   totalSourceBytes                571698 non-null  int64
 3   totalDestinationBytes           571698 non-null  int64
 4   totalDestinationPackets         571698 non-null  int64
 5   totalSourcePackets              571698 non-null  int64
 6   sourcePayloadAsBase64           302046 non-null  object
 7   sourcePayloadAsUTF              302043 non-null  object
 8   destinationPayloadAsBase64      246132 non-null  object
 9   destinationPayloadAsUTF         246126 non-null  object
 10  direction                       571698 non-null  object
 11  sourceTCPFlagsDescription       440931 non-null  object
 12  destinationTCPFlagsDescription  422482 non-null  object
 13  source                          571698 non-null  object
 14  protocolName                    571698 non-null  object
 15  sourcePort                      571698 non-null  int64
 16  destination                     571698 non-null  object
 17  destinationPort                 571698 non-null  int64
 18  startDateTime                   571698 non-null  object
 19  stopDateTime                    571698 non-null  object
 20  Label                           571698 non-null  object
dtypes: int64(6), object(15)
memory usage: 91.6+ MB

In [ ]:
df2.isnull().sum()

generated                              0
appName                                0
totalSourceBytes                       0
totalDestinationBytes                  0
totalDestinationPackets                0
totalSourcePackets                     0
sourcePayloadAsBase64             269652
sourcePayloadAsUTF                269655
destinationPayloadAsBase64        325566
destinationPayloadAsUTF           325572
direction                              0
sourceTCPFlagsDescription         130767
destinationTCPFlagsDescription    149216
source                                 0
protocolName                           0
sourcePort                             0
destination                            0
destinationPort                        0
startDateTime                          0
stopDateTime                           0
Label                                  0
dtype: int64

In [ ]:
df = pd.concat([df1, df2], ignore_index=True)
df.info()
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743078 entries, 0 to 743077
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   generated                       743078 non-null  object
 1   appName                         743078 non-null  object
 2   totalSourceBytes                743078 non-null  int64
 3   totalDestinationBytes           743078 non-null  int64
 4   totalDestinationPackets         743078 non-null  int64
 5   totalSourcePackets              743078 non-null  int64
 6   sourcePayloadAsBase64           386625 non-null  object
 7   sourcePayloadAsUTF              302043 non-null  object
 8   destinationPayloadAsBase64      320766 non-null  object
 9   destinationPayloadAsUTF         320742 non-null  object
 10  direction                       743078 non-null  object
 11  sourceTCPFlagsDescription       563005 non-null  object
 12  destinationTCPFlagsDescription  539879 non-null  object
 13  source                          743078 non-null  object
 14  protocolName                    743078 non-null  object
 15  sourcePort                      743078 non-null  int64
 16  destination                     743078 non-null  object
 17  destinationPort                 743078 non-null  int64
 18  startDateTime                   743078 non-null  object
 19  stopDateTime                    743078 non-null  object
 20  Label                           743078 non-null  object
dtypes: int64(6), object(15)
memory usage: 119.1+ MB

,generated,appName,totalSourceBytes,totalDestinationBytes,totalDestinationPackets,totalSourcePackets,sourcePayloadAsBase64,sourcePayloadAsUTF,destinationPayloadAsBase64,destinationPayloadAsUTF,...,sourceTCPFlagsDescription,destinationTCPFlagsDescription,source,protocolName,sourcePort,destination,destinationPort,startDateTime,stopDateTime,Label
0,3/11/2014 18:21,Unknown_UDP,16076,0,0,178,NaN,NaN,NaN,NaN,...,NaN,NaN,192.168.5.122,udp_ip,5353,224.0.0.251,5353,6/13/2010 23:57,6/14/2010 0:11,Normal
1,3/11/2014 18:21,HTTPImageTransfer,384,0,0,6,NaN,NaN,NaN,NaN,...,"F,A",NaN,192.168.2.111,tcp_ip,4435,206.217.198.186,80,6/13/2010 23:58,6/14/2010 0:01,Normal
2,3/11/2014 18:21,DNS,171,642,4,2,NaN,NaN,NaN,NaN,...,NaN,NaN,192.168.4.119,udp_ip,4428,192.168.5.122,53,6/13/2010 23:58,6/13/2010 23:59,Normal
3,3/11/2014 18:21,HTTPImageTransfer,384,0,0,6,NaN,NaN,NaN,NaN,...,"F,A",NaN,192.168.4.119,tcp_ip,3639,219.94.203.105,80,6/13/2010 23:58,6/14/2010 0:00,Normal
4,3/11/2014 18:21,HTTPImageTransfer,186,128,2,2,NaN,NaN,NaN,NaN,...,"F,P,A",R,192.168.4.119,tcp_ip,3641,98.137.80.50,80,6/13/2010 23:58,6/13/2010 23:59,Normal

In [ ]:
df['Label'].value_counts()

Label
Normal    701842
Attack     41236
Name: count, dtype: int64

In [ ]:
drop_cols = [
    'sourcePayloadAsBase64', 'sourcePayloadAsUTF',
    'destinationPayloadAsBase64', 'destinationPayloadAsUTF',
    'generated', 'appName'
]
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

In [ ]:
df['startDateTime'] = pd.to_datetime(df['startDateTime'])
df['stopDateTime'] = pd.to_datetime(df['stopDateTime'])
df = df.sort_values('startDateTime').reset_index(drop=True)

In [ ]:
df['duration'] = (df['stopDateTime'] - df['startDateTime']).dt.total_seconds().clip(lower=0.001)

df['packets_per_second'] = (df['totalSourcePackets'] + df['totalDestinationPackets']) / df['duration']
df['bytes_per_second'] = (df['totalSourceBytes'] + df['totalDestinationBytes']) / df['duration']

df['flags'] = df['sourceTCPFlagsDescription'].fillna('')
df['syn_ratio'] = df['flags'].str.contains('S').astype(int)
df['rst_ratio'] = df['flags'].str.contains('R').astype(int)

df = df.set_index('startDateTime')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 743078 entries, 2010-06-13 23:57:00 to 2010-06-15 23:58:00
Data columns (total 20 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   totalSourceBytes                743078 non-null  int64
 1   totalDestinationBytes           743078 non-null  int64
 2   totalDestinationPackets         743078 non-null  int64
 3   totalSourcePackets              743078 non-null  int64
 4   direction                       743078 non-null  object
 5   sourceTCPFlagsDescription       563005 non-null  object
 6   destinationTCPFlagsDescription  539879 non-null  object
 7   source                          743078 non-null  object
 8   protocolName                    743078 non-null  object
 9   sourcePort                      743078 non-null  int64
 10  destination                     743078 non-null  object
 11  destinationPort                 743078 non-null  int64
 12  stopDateTime                    743078 non-null  datetime64[ns]
 13  Label                           743078 non-null  object
 14  duration                        743078 non-null  float64
 15  packets_per_second              743078 non-null  float64
 16  bytes_per_second                743078 non-null  float64
 17  flags                           743078 non-null  object
 18  syn_ratio                       743078 non-null  int64
 19  rst_ratio                       743078 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(8), object(8)
memory usage: 119.1+ MB

In [ ]:
df.describe()

,totalSourceBytes,totalDestinationBytes,totalDestinationPackets,totalSourcePackets,sourcePort,destinationPort,stopDateTime,duration,packets_per_second,bytes_per_second,syn_ratio,rst_ratio
count,7.430780e+05,7.430780e+05,743078.000000,743078.000000,743078.000000,743078.000000,743078,743078.000000,7.430780e+05,7.430780e+05,743078.000000,743078.000000
mean,3.979638e+03,3.906708e+04,36.994150,23.059224,15666.892746,4297.038639,2010-06-15 06:23:50.952174848,16.323811,3.245561e+04,2.076326e+07,0.687088,0.017367
min,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,2010-06-13 23:59:00,0.001000,2.824859e-04,2.937853e-02,0.000000,0.000000
25%,2.560000e+02,3.230000e+02,1.000000,3.000000,2350.000000,80.000000,2010-06-15 01:37:00,0.001000,2.000000e+03,2.220000e+05,0.000000,0.000000
50%,4.770000e+02,1.376000e+03,6.000000,6.000000,3848.000000,80.000000,2010-06-15 10:10:00,0.001000,1.000000e+04,1.224000e+06,1.000000,0.000000
75%,9.020000e+02,8.904000e+03,12.000000,11.000000,22252.000000,80.000000,2010-06-15 15:26:00,0.001000,1.400000e+04,4.653000e+06,1.000000,0.000000
max,7.632776e+08,3.955996e+08,538228.000000,514794.000000,65534.000000,65535.000000,2010-06-15 23:58:00,14340.000000,1.832500e+07,1.211823e+10,1.000000,1.000000
std,1.252821e+06,7.163688e+05,1017.296493,887.117348,21702.660183,13110.490013,NaN,111.922845,1.063167e+05,8.322250e+07,0.463679,0.130634

In [ ]:
def calculate_entropy(ip_series):
    counts = ip_series.value_counts(normalize=True)
    return -(counts * np.log2(counts)).sum()

# Create a strict 5-second boundary mapping for accurate merging
df['time_bucket'] = df.index.floor('5s')

# Group traffic into 5-second tumbling windows per destination IP
windowed_features = df.groupby(['destination', 'time_bucket']).agg(
    unique_source_ips=('source', 'nunique'),
    source_ip_entropy=('source', calculate_entropy)
).reset_index()

# Merge the calculated 5-second window features back into the main flow dataframe
df = df.reset_index().merge(windowed_features, on=['destination', 'time_bucket'], how='left')
df = df.drop(columns=['time_bucket'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 743078 entries, 0 to 743077
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   startDateTime                   743078 non-null  datetime64[ns]
 1   totalSourceBytes                743078 non-null  int64
 2   totalDestinationBytes           743078 non-null  int64
 3   totalDestinationPackets         743078 non-null  int64
 4   totalSourcePackets              743078 non-null  int64
 5   direction                       743078 non-null  object
 6   sourceTCPFlagsDescription       563005 non-null  object
 7   destinationTCPFlagsDescription  539879 non-null  object
 8   source                          743078 non-null  object
 9   protocolName                    743078 non-null  object
 10  sourcePort                      743078 non-null  int64
 11  destination                     743078 non-null  object
 12  destinationPort                 743078 non-null  int64
 13  stopDateTime                    743078 non-null  datetime64[ns]
 14  Label                           743078 non-null  object
 15  duration                        743078 non-null  float64
 16  packets_per_second              743078 non-null  float64
 17  bytes_per_second                743078 non-null  float64
 18  flags                           743078 non-null  object
 19  syn_ratio                       743078 non-null  int64
 20  rst_ratio                       743078 non-null  int64
 21  unique_source_ips               743078 non-null  int64
 22  source_ip_entropy               743078 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(9), object(8)
memory usage: 130.4+ MB

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

# 1. Extract the date directly from the datetime column
df['date_only'] = df['startDateTime'].dt.date

# 2. One-hot encode the categorical features BEFORE splitting
df = pd.get_dummies(df, columns=['protocolName', 'direction'], drop_first=True)

X_train_chunks, X_test_chunks = [], []
y_train_chunks, y_test_chunks = [], []

# 3. Group by the exact day (June 14 vs June 15)
for date, daily_data in df.groupby('date_only'):

    # Drop all raw metadata, original counters, identifiers, and the target Label
    X_daily = daily_data.drop(columns=[
        'startDateTime', 'stopDateTime', 'source', 'destination',
        'sourcePort', 'destinationPort', 'sourceTCPFlagsDescription',
        'destinationTCPFlagsDescription', 'flags', 'duration',
        'totalSourceBytes', 'totalDestinationBytes',
        'totalDestinationPackets', 'totalSourcePackets',
        'Label', 'date_only'
    ], errors='ignore')

    # Convert string labels to binary
    y_daily = daily_data['Label'].apply(lambda x: 0 if x == 'Normal' else 1)

    # Chronological split for THIS day (no shuffling)
    X_tr, X_te, y_tr, y_te = train_test_split(X_daily, y_daily, test_size=0.2, shuffle=False)

    X_train_chunks.append(X_tr)
    X_test_chunks.append(X_te)
    y_train_chunks.append(y_tr)
    y_test_chunks.append(y_te)

# 4. Combine the chunks back into final Train and Test sets
X_train = pd.concat(X_train_chunks)
X_test = pd.concat(X_test_chunks)
y_train = pd.concat(y_train_chunks)
y_test = pd.concat(y_test_chunks)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 594461 entries, 0 to 628758
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   packets_per_second   594461 non-null  float64
 1   bytes_per_second     594461 non-null  float64
 2   syn_ratio            594461 non-null  int64
 3   rst_ratio            594461 non-null  int64
 4   unique_source_ips    594461 non-null  int64
 5   source_ip_entropy    594461 non-null  float64
 6   protocolName_igmp    594461 non-null  bool
 7   protocolName_ip      594461 non-null  bool
 8   protocolName_tcp_ip  594461 non-null  bool
 9   protocolName_udp_ip  594461 non-null  bool
 10  direction_L2R        594461 non-null  bool
 11  direction_R2L        594461 non-null  bool
 12  direction_R2R        594461 non-null  bool
dtypes: bool(7), float64(3), int64(3)
memory usage: 35.7 MB

In [ ]:
import pandas as pd

# Combine X_train and y_train temporarily to undersample safely
train_df = X_train.copy()
train_df['Label'] = y_train

# Separate normal and attack rows in the training set
normal_df = train_df[train_df['Label'] == 0]
attack_df = train_df[train_df['Label'] == 1]

# Downsample normal rows to a 3:1 ratio against the attacks
normal_downsampled = normal_df.sample(n=len(attack_df) * 3, random_state=42)

# Recombine and shuffle just the training partition
balanced_train = pd.concat([normal_downsampled, attack_df]).sample(frac=1, random_state=42)

# Separate back into X_train and y_train
X_train = balanced_train.drop(columns=['Label'])
y_train = balanced_train['Label']

In [ ]:
X_train.shape

(129744, 13)

In [ ]:
y_train.value_counts()

Label
0    97308
1    32436
Name: count, dtype: int64

In [ ]:
X_train.describe()

,packets_per_second,bytes_per_second,syn_ratio,rst_ratio,unique_source_ips,source_ip_entropy
count,1.297440e+05,1.297440e+05,129744.000000,129744.000000,129744.000000,129744.000000
mean,7.980702e+04,5.166989e+07,0.745352,0.014729,5.085800,1.040480
std,1.231469e+05,8.843970e+07,0.435665,0.120466,6.032913,1.287649
min,8.620690e-04,8.965517e-02,0.000000,0.000000,1.000000,-0.000000
25%,2.000000e+03,3.040000e+05,0.000000,0.000000,1.000000,-0.000000
50%,1.200000e+04,2.493500e+06,1.000000,0.000000,1.000000,-0.000000
75%,2.130000e+05,1.684690e+08,1.000000,0.000000,12.000000,2.732321
max,6.698000e+06,6.987076e+09,1.000000,1.000000,84.000000,6.279715

In [ ]:
from sklearn.preprocessing import RobustScaler

# Define only the continuous numerical columns
continuous_cols = ['packets_per_second', 'bytes_per_second', 'unique_source_ips', 'source_ip_entropy']

# Initialize and apply RobustScaler
scaler = RobustScaler()
X_train[continuous_cols] = scaler.fit_transform(X_train[continuous_cols])
X_test[continuous_cols] = scaler.transform(X_test[continuous_cols])

# Verify the fix (The 50% row for these columns should now be 0.0)
print(X_train[continuous_cols].describe())

       packets_per_second  bytes_per_second  unique_source_ips  \
count       129744.000000     129744.000000      129744.000000
mean             0.321360          0.292429           0.371436
std              0.583634          0.525910           0.548447
min             -0.056872         -0.014828           0.000000
25%             -0.047393         -0.013020           0.000000
50%              0.000000          0.000000           0.000000
75%              0.952607          0.986980           1.000000
max             31.687204         41.534103           7.545455

       source_ip_entropy
count      129744.000000
mean            0.380804
std             0.471266
min            -0.000000
25%            -0.000000
50%            -0.000000
75%             1.000000
max             2.298308

In [ ]:
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Safety net: Sanitize any lingering Infinities
X_train = X_train.replace([np.inf, -np.inf], np.nan).fillna(0)
X_test = X_test.replace([np.inf, -np.inf], np.nan).fillna(0)

# 1. Calculate the dynamic imbalance ratio
imbalance_ratio = (y_train == 0).sum() / (y_train == 1).sum()

# 2. Initialize the model (using histogram optimization for speed)
model = XGBClassifier(
    scale_pos_weight=imbalance_ratio,
    tree_method='hist',
    device='cuda', # Change to 'device="cpu"' if you didn't switch your Colab runtime to T4 GPU
    random_state=42,
    eval_metric='logloss'
)

# 3. Train the model
print("Training model... this might take a minute.")
model.fit(X_train, y_train)

# 4. Generate predictions and evaluate performance
y_pred = model.predict(X_test)

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Training model... this might take a minute.

Confusion Matrix:
 [[139162    655]
 [  3232   5568]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99    139817
           1       0.89      0.63      0.74      8800

    accuracy                           0.97    148617
   macro avg       0.94      0.81      0.86    148617
weighted avg       0.97      0.97      0.97    148617

/usr/local/lib/python3.13/dist-packages/xgboost/core.py:569: UserWarning: [12:36:07] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

In [ ]:
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Safety net: Sanitize any lingering Infinities
X_train = X_train.replace([np.inf, -np.inf], np.nan).fillna(0)
X_test = X_test.replace([np.inf, -np.inf], np.nan).fillna(0)

# 1. Calculate the dynamic imbalance ratio
imbalance_ratio = (y_train == 0).sum() / (y_train == 1).sum()

# 2. Initialize the model (using histogram optimization for speed)
model = XGBClassifier(
    scale_pos_weight=imbalance_ratio,
    tree_method='hist',
    device='cuda', # Change to 'device="cpu"' if you didn't switch your Colab runtime to T4 GPU
    random_state=42,
    eval_metric='logloss'
)

# 3. Train the model
print("Training model... this might take a minute.")
model.fit(X_train, y_train)

# 4. Generate prediction probabilities for the positive class (Attack)
y_probs = model.predict_proba(X_test)[:, 1]

# 5. Apply manual threshold (e.g., 0.3 instead of the default 0.5)
custom_threshold = 0.0
y_pred_custom = (y_probs >= custom_threshold).astype(int)

# 6. Evaluate performance with the custom threshold
print("\nCustom Threshold Confusion Matrix:\n", confusion_matrix(y_test, y_pred_custom))
print("\nCustom Threshold Classification Report:\n", classification_report(y_test, y_pred_custom))

Training model... this might take a minute.

Custom Threshold Confusion Matrix:
 [[     0 139817]
 [     0   8800]]

Custom Threshold Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00    139817
           1       0.06      1.00      0.11      8800

    accuracy                           0.06    148617
   macro avg       0.03      0.50      0.06    148617
weighted avg       0.00      0.06      0.01    148617

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import numpy as np
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Safety net: Sanitize any lingering Infinities
X_train = X_train.replace([np.inf, -np.inf], np.nan).fillna(0)
X_test = X_test.replace([np.inf, -np.inf], np.nan).fillna(0)

# Use a moderated scale_pos_weight (e.g., 5.0 instead of the full extreme ratio)
# to prevent probability compression and massive false-positive spikes.
model = XGBClassifier(
    scale_pos_weight=5.0,
    tree_method='hist',
    device='cuda',
    random_state=42,
    eval_metric='logloss'
)

# Train the model
print("Training model with production-tuned weights...")
model.fit(X_train, y_train)

# Generate raw probabilities
y_probs = model.predict_proba(X_test)[:, 1]

# Apply a realistic, operational threshold (0.3) suitable for a streaming pipeline
production_threshold = 0.1
y_pred_prod = (y_probs >= production_threshold).astype(int)

# Evaluate performance
print("\nProduction-Tuned Confusion Matrix:\n", confusion_matrix(y_test, y_pred_prod))
print("\nProduction-Tuned Classification Report:\n", classification_report(y_test, y_pred_prod))

Training model with production-tuned weights...

Production-Tuned Confusion Matrix:
 [[139035    782]
 [  3026   5774]]

Production-Tuned Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.99      0.99    139817
           1       0.88      0.66      0.75      8800

    accuracy                           0.97    148617
   macro avg       0.93      0.83      0.87    148617
weighted avg       0.97      0.97      0.97    148617

In [ ]:
import joblib

# 1. Save the trained XGBoost model
joblib.dump(model, 'xgboost_ddos_model.pkl')

# 2. Save the fitted RobustScaler so live streams are scaled identically
joblib.dump(scaler, 'robust_scaler.pkl')

print("Model and scaler successfully exported to disk!")

Model and scaler successfully exported to disk!